blank_issues_enabled: false
contact_links:
  - name: Aerie Backend
    url: https://github.com/NASA-AMMOS/aerie/issues/new/choose
    about: Issues and feature requests for the main Aerie repo (not UI related).
  - name: Slack Chat
    url: https://jpl.slack.com/archives/C0163E42UBF
    about: Ask questions and discuss with other Aerie users in real time.
